# –*–coding:utf-8 –*–
# 2021-12-07 15:00
import time

from selenium.webdriver.common.by import By
from selenium.webdriver import ActionChains
from langyun_automate.langyun.page.webdriver_initialzation import CaseLogin

'''
职工考勤
'''
class staff_attendance(CaseLogin):
    def test_edit_shift(self): # 编辑班次
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-3 div").click()
        self.driver.find_element(By.CSS_SELECTOR, "#li-4 div").click()
        self.driver.find_element(By.LINK_TEXT, "班次管理").click()
        self.driver.switch_to.frame(4)
        self.driver.find_element(By.LINK_TEXT, "2").click()
        self.driver.find_element(By.CSS_SELECTOR, ".text-c:nth-child(10) .cl-tb:nth-child(1)").click()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.NAME, "weekday[]").click()
        self.driver.find_element(By.ID, "_punch3").click()
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) li:nth-child(17)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".laydate-btns-confirm").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.close()

    def test_add_shift(self): # 添加班次
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-4 .img-responsive:nth-child(1)").click()
        self.driver.find_element(By.LINK_TEXT, "班次管理").click()
        self.driver.switch_to.frame(3)
        self.driver.find_element(By.LINK_TEXT, "添加班次 ").click()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.NAME, "name").click()
        self.driver.find_element(By.NAME, "name").send_keys("Test班次")
        self.driver.find_element(By.NAME, "start_time").click()
        self.driver.find_element(By.CSS_SELECTOR, ".laydate-btns-confirm").click()
        self.driver.find_element(By.CSS_SELECTOR, ".col-xs-7 > .qianhui").click()
        self.driver.find_element(By.ID, "_punch1").click()
        self.driver.find_element(By.ID, "_punch1").send_keys("10:00")
        self.driver.find_element(By.ID, "_punch2").click()
        self.driver.find_element(By.ID, "_punch2").send_keys("10:30")
        self.driver.find_element(By.ID, "_punch3").click()
        self.driver.find_element(By.ID, "_punch3").send_keys("14:00")
        self.driver.find_element(By.ID, "_punch4").click()
        self.driver.find_element(By.ID, "_punch4").send_keys("18:00")
        self.driver.find_element(By.CSS_SELECTOR, ".col-xs-2:nth-child(5) > input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".col-xs-2:nth-child(6)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".col-xs-2:nth-child(7) > input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".col-xs-2:nth-child(2) > input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.close()

    def test_delete_shift(self): # 删除班次
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-4 .img-responsive:nth-child(1)").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "#li-4 .img-responsive:nth-child(1)")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.LINK_TEXT, "班次管理").click()
        self.driver.switch_to.frame(3)
        self.driver.find_element(By.LINK_TEXT, "2").click()
        self.driver.find_element(By.CSS_SELECTOR, ".text-c:nth-child(10) .cl-tb:nth-child(2)").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".text-c:nth-child(10) .cl-tb:nth-child(2)")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.LINK_TEXT, "确定").click()
        self.driver.close()

    def test_Scheduling(self): #  排班
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-4 .img-responsive:nth-child(1)").click()
        self.driver.find_element(By.LINK_TEXT, "班次管理").click()
        element = self.driver.find_element(By.LINK_TEXT, "班次管理")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.switch_to.frame(3)
        self.driver.find_element(By.LINK_TEXT, "排班").click()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2)").click()
        self.driver.find_element(By.CSS_SELECTOR, "#shuttle_box_left > li:nth-child(3)").click()
        self.driver.find_element(By.CSS_SELECTOR, "#shuttle_box_left > li:nth-child(5)").click()
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(6)").click()
        self.driver.find_element(By.CSS_SELECTOR, "#shuttle_box_toRight > span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".bluebtn").click()
        self.driver.close()

    def test_edit_False_attendance(self): #编辑假勤
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.LINK_TEXT, "职工考勤").click()
        self.driver.find_element(By.LINK_TEXT, "考勤设置").click()
        self.driver.switch_to.frame(3)
        self.driver.find_element(By.LINK_TEXT, "假勤类型设置").click()
        self.driver.find_element(By.LINK_TEXT, "添加假勤类型 ").click()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.CSS_SELECTOR, ".btn-default").click()
        self.driver.switch_to.default_content()
        self.driver.find_element(By.CSS_SELECTOR, ".text-c:nth-child(10) .btn:nth-child(1)").click()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.NAME, "name").click()
        self.driver.find_element(By.NAME, "name").send_keys("Test假勤")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".btn-primary")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.close()


    def test_edit_Attendance_rules(self):# 编辑考勤规则
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-4 div").click()
        self.driver.find_element(By.LINK_TEXT, "考勤设置").click()
        self.driver.switch_to.frame(3)
        self.driver.find_element(By.LINK_TEXT, "编辑").click()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.NAME, "interval_minutes_between_attendance").send_keys("1")
        self.driver.find_element(By.NAME, "interval_minutes_between_attendance").click()
        self.driver.find_element(By.NAME, "interval_minutes_between_attendance").send_keys("2")
        self.driver.find_element(By.NAME, "interval_minutes_between_attendance").click()
        self.driver.find_element(By.NAME, "interval_minutes_between_attendance").send_keys("3")
        self.driver.find_element(By.NAME, "interval_minutes_between_attendance").click()
        element = self.driver.find_element(By.NAME, "interval_minutes_between_attendance")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.NAME, "interval_minutes_between_attendance").send_keys("4")
        self.driver.find_element(By.NAME, "interval_minutes_between_attendance").click()
        self.driver.find_element(By.NAME, "interval_minutes_between_attendance").send_keys("5")
        self.driver.find_element(By.NAME, "interval_minutes_between_attendance").click()
        self.driver.find_element(By.NAME, "interval_minutes_between_attendance").send_keys("6")
        self.driver.find_element(By.NAME, "interval_minutes_between_attendance").click()
        self.driver.find_element(By.NAME, "interval_minutes_between_attendance").send_keys("7")
        self.driver.find_element(By.NAME, "interval_minutes_between_attendance").click()
        self.driver.find_element(By.NAME, "interval_minutes_between_attendance").send_keys("8")
        self.driver.find_element(By.NAME, "interval_minutes_between_attendance").click()
        self.driver.find_element(By.NAME, "late_limit").click()
        self.driver.find_element(By.NAME, "late_limit").send_keys("30")
        self.driver.find_element(By.NAME, "absent_late_limit").click()
        self.driver.find_element(By.NAME, "reissue_card_limit").click()
        self.driver.find_element(By.NAME, "reissue_card_limit").send_keys("1")
        self.driver.find_element(By.NAME, "early_limit").click()
        self.driver.find_element(By.NAME, "early_limit").send_keys("5")
        self.driver.find_element(By.NAME, "absent_early_limit").click()
        self.driver.find_element(By.NAME, "absent_early_limit").send_keys("10")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.find_element(By.LINK_TEXT, "确定").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".btn-primary")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.LINK_TEXT, "确定").click()
        self.driver.find_element(By.NAME, "early_limit").click()
        self.driver.find_element(By.NAME, "early_limit").send_keys("25")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".btn-primary")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.LINK_TEXT, "确定").click()
        self.driver.find_element(By.NAME, "absent_early_limit").click()
        self.driver.find_element(By.NAME, "absent_early_limit").send_keys("5")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.find_element(By.LINK_TEXT, "确定").click()
        self.driver.find_element(By.NAME, "early_limit").click()
        self.driver.find_element(By.NAME, "early_limit").send_keys("5")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".btn-primary")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.LINK_TEXT, "确定").click()
        self.driver.find_element(By.NAME, "absent_early_limit").click()
        self.driver.find_element(By.NAME, "absent_early_limit").send_keys("20")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".btn-primary")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.LINK_TEXT, "确定").click()
        self.driver.find_element(By.NAME, "early_limit").send_keys("6")
        self.driver.find_element(By.NAME, "early_limit").click()
        self.driver.find_element(By.NAME, "early_limit").send_keys("7")
        self.driver.find_element(By.NAME, "early_limit").click()
        element = self.driver.find_element(By.NAME, "early_limit")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".btn-primary")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        time.sleep(3)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".layui-layer-close").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-default").click()
        self.driver.switch_to.default_content()
        self.driver.find_element(By.LINK_TEXT, "编辑").click()
        element = self.driver.find_element(By.LINK_TEXT, "编辑")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".btn-primary")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()

    def test_look_Personal_report(self): # 查看个人报表
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-4 div").click()
        self.driver.switch_to.frame(2)
        self.driver.find_element(By.LINK_TEXT, "考勤报表").click()
        self.driver.switch_to.default_content()
        self.driver.find_element(By.LINK_TEXT, "全园报表").click()
        self.driver.switch_to.frame(2)
        self.driver.find_element(By.LINK_TEXT, "出勤率分析").click()
        self.driver.find_element(By.LINK_TEXT, "刷卡记录").click()
        self.driver.find_element(By.LINK_TEXT, "考勤明细").click()

    def test_delete_False_attendance(self):# 删除假勤
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-4 .img-responsive:nth-child(1)").click()
        self.driver.find_element(By.LINK_TEXT, "班次管理").click()
        element = self.driver.find_element(By.LINK_TEXT, "班次管理")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.switch_to.frame(3)
        self.driver.find_element(By.LINK_TEXT, "排班").click()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2)").click()
        self.driver.find_element(By.CSS_SELECTOR, "#shuttle_box_left > li:nth-child(3)").click()
        self.driver.find_element(By.CSS_SELECTOR, "#shuttle_box_left > li:nth-child(5)").click()
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(6)").click()
        self.driver.find_element(By.CSS_SELECTOR, "#shuttle_box_toRight > span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".bluebtn").click()
        self.driver.close()

    def test_add_False_attendance(self):# 添加假勤
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-4 div").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "#li-4 div")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        # body
        element = self.driver.find_element(By.CSS_SELECTOR, "body").click()
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.LINK_TEXT, "考勤设置").click()
        self.driver.switch_to.frame(3)
        self.driver.find_element(By.LINK_TEXT, "假勤类型设置").click()
        self.driver.find_element(By.LINK_TEXT, "添加假勤类型 ").click()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.NAME, "name").click()
        self.driver.find_element(By.NAME, "name").send_keys("测试假勤")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".btn-primary")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.close()