# –*–coding:utf-8 –*–
# 2021-12-07 14:32
from selenium.webdriver import ActionChains

from langyun_automate.langyun.page.webdriver_initialzation import CaseLogin
from selenium.webdriver.common.by import By

'''
职工管理
'''
class staff_management(CaseLogin):
    def test_edit_Elegant_demeanor(self):# 编辑风采
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-3 div").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "#li-3 div")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.LINK_TEXT, "教师风采").click()
        self.driver.switch_to.frame(3)
        self.driver.find_element(By.CSS_SELECTOR, ".col-md-2:nth-child(4) .btn-edit .notice-ms").click()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.NAME, "honor").click()
        self.driver.find_element(By.NAME, "honor").send_keys("11111")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-secondary").click()
        self.driver.close()

    def test_edit_maagement(self): # 编辑职工
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-3 .img-responsive:nth-child(1)").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "#li-3 .img-responsive:nth-child(1)")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.switch_to.frame(2)
        self.driver.find_element(By.LINK_TEXT, "编辑").click()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.CSS_SELECTOR, ".select-box").click()
        self.driver.find_element(By.ID, "role").click()
        dropdown = self.driver.find_element(By.ID, "role")
        dropdown.find_element(By.XPATH, "//option[. = '全部权限节点都有']").click()
        self.driver.find_element(By.ID, "role").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-secondary").click()

    def test_edit_authority_name(self):# 编辑职位权限名称
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.LINK_TEXT, "职工管理").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "#li-3 .img-responsive:nth-child(1)")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.LINK_TEXT, "职位权限").click()
        self.driver.switch_to.frame(3)
        self.driver.find_element(By.LINK_TEXT, "编辑").click()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.NAME, "name").click()
        self.driver.find_element(By.NAME, "name").click()
        self.driver.find_element(By.NAME, "name").send_keys("职位权限")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()

    def test_select_authority_name(self): # 查询职位名称
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-3 .img-responsive:nth-child(1)").click()
        self.driver.find_element(By.LINK_TEXT, "职位权限").click()
        element = self.driver.find_element(By.LINK_TEXT, "职位权限")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.switch_to.frame(3)
        self.driver.find_element(By.NAME, "name").click()
        self.driver.find_element(By.NAME, "name").send_keys("主任")
        self.driver.find_element(By.CSS_SELECTOR, "#cx > .Hui-iconfont").click()
        self.driver.close()

    def test_select_Elegant_demeanor(self): # 查询已有风采
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.LINK_TEXT, "职工管理").click()
        self.driver.find_element(By.LINK_TEXT, "教师风采").click()
        self.driver.switch_to.frame(3)
        self.driver.find_element(By.NAME, "name").click()
        self.driver.find_element(By.NAME, "name").send_keys("张")
        self.driver.find_element(By.CSS_SELECTOR, "#cx > span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".teacherPic > img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".layui-layer-close").click()
        self.driver.close()

    def test_select_staff(self): # 查询教职工
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-3 div").click()
        self.driver.switch_to.frame(2)
        self.driver.find_element(By.NAME, "name").click()
        self.driver.find_element(By.NAME, "name").send_keys("老师")
        self.driver.find_element(By.ID, "cx").click()

    def test_add_Elegant_demeanor(self): # 新增风采
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-3 div").click()
        self.driver.find_element(By.LINK_TEXT, "教师风采").click()
        self.driver.switch_to.frame(3)
        self.driver.find_element(By.LINK_TEXT, "创建风采").click()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.NAME, "classId").click()
        dropdown = self.driver.find_element(By.NAME, "classId")
        dropdown.find_element(By.XPATH, "//option[. = '小星星小班']").click()
        self.driver.find_element(By.NAME, "classId").click()
        self.driver.find_element(By.NAME, "motto").click()
        self.driver.find_element(By.NAME, "motto").send_keys("教育就是力量")
        self.driver.find_element(By.NAME, "honor").click()
        self.driver.find_element(By.NAME, "honor").send_keys("教育就是力量")
        self.driver.find_element(By.CSS_SELECTOR, "#uploadifive-upload_ablums > input:nth-child(3)").click()
        self.driver.find_element(By.CSS_SELECTOR, "#uploadifive-upload_ablums > input:nth-child(3)").send_keys(
                "C:\\fakepath\\1.jpeg")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-secondary").click()

    def test_import_staff(self): #导入职工
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-3 .img-responsive:nth-child(1)").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "#li-3 .img-responsive:nth-child(1)")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.switch_to.frame(2)
        self.driver.find_element(By.LINK_TEXT, "模板导入").click()
        self.driver.find_element(By.ID, "importEasyFile").click()
        self.driver.find_element(By.ID, "importEasyFile").send_keys("C:\\fakepath\\teacherTemplate.xlsx")
        self.driver.find_element(By.LINK_TEXT, "确定").click()

    def test_del_teacher_Elegant_demeanor(self):# 删除教师风采
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-3 .img-responsive:nth-child(1)").click()
        self.driver.find_element(By.LINK_TEXT, "教师风采").click()
        self.driver.switch_to.frame(3)
        self.driver.find_element(By.CSS_SELECTOR, ".show-text").click()
        self.driver.find_element(By.ID, "batch-delete").click()
        self.driver.find_element(By.LINK_TEXT, "确定").click()
        self.driver.close()

    def test_authority_name(self): # 删除权限名称
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-3 div").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "#li-3 div")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.LINK_TEXT, "职位权限").click()
        element = self.driver.find_element(By.LINK_TEXT, "职位权限")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.switch_to.frame(3)
        self.driver.find_element(By.LINK_TEXT, "删除").click()
        element = self.driver.find_element(By.LINK_TEXT, "删除")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.LINK_TEXT, "确定").click()
        self.driver.close()

    def test_del_staff(self): # 删除教职工
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-3 .img-responsive:nth-child(1)").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "#li-3 .img-responsive:nth-child(1)")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.switch_to.frame(2)
        self.driver.find_element(By.CSS_SELECTOR, ".text-c:nth-child(1) > td:nth-child(1)").click()
        self.driver.find_element(By.NAME, "id").click()
        self.driver.find_element(By.CSS_SELECTOR, ".text-c:nth-child(3) > td:nth-child(1)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".text-c:nth-child(3) input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".text-c:nth-child(4) input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".text-c:nth-child(5) input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".text-c:nth-child(6) input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".text-c:nth-child(7) input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".text-c:nth-child(8) input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".text-c:nth-child(9) input").click()
        self.driver.find_element(By.ID, "batch-delete").click()
        self.driver.find_element(By.LINK_TEXT, "确定").click()

    def test_empower_authority(self):# 授权职位信息
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-4 div").click()
        self.driver.find_element(By.CSS_SELECTOR, "#li-3 div").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "#li-3 div")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.LINK_TEXT, "职位权限").click()
        element = self.driver.find_element(By.LINK_TEXT, "职位权限")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.switch_to.frame(4)
        self.driver.find_element(By.LINK_TEXT, "授权").click()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(4) > input").click()
        self.driver.find_element(By.ID, "sex-6").click()
        self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(6) .radio-box:nth-child(4)").click()
        self.driver.find_element(By.ID, "sex-54").click()
        self.driver.find_element(By.ID, "sex-28").click()
        self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(18) .radio-box:nth-child(3) > label").click()
        self.driver.find_element(By.ID, "sub").click()
        self.driver.find_element(By.LINK_TEXT, "确认授权").click()

    def test_add_authority_name(self):# 添加职位名称
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-3 div").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "#li-3 div")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.LINK_TEXT, "职位权限").click()
        element = self.driver.find_element(By.LINK_TEXT, "职位权限")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.switch_to.frame(3)
        self.driver.find_element(By.CSS_SELECTOR, ".btn-warning > .Hui-iconfont").click()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.NAME, "name").click()
        self.driver.find_element(By.NAME, "name").send_keys("测试职位权限")
        self.driver.find_element(By.NAME, "remark").click()
        self.driver.find_element(By.NAME, "remark").send_keys("测试用的")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()

    def test_add_staff(self): #添加职工
        self.driver.set_window_size(1226, 902)
        self.driver.find_element(By.NAME, "account").click()
        self.driver.find_element(By.NAME, "account").send_keys("13006662818")
        self.driver.find_element(By.NAME, "password").send_keys("langyun")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-secondary").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".btn-secondary")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR, "#li-3 div").click()
        self.driver.switch_to.frame(2)
        self.driver.find_element(By.LINK_TEXT, "添加职工 ").click()
        element = self.driver.find_element(By.LINK_TEXT, "添加职工 ")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.NAME, "username").click()
        self.driver.find_element(By.NAME, "username").send_keys("测试刘老师")
        self.driver.find_element(By.NAME, "phone").click()
        self.driver.find_element(By.NAME, "phone").send_keys("16753892110")
        self.driver.find_element(By.NAME, "phone").send_keys("16753892111")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-secondary").click()

    def test_pages_staff(self):
        # 职工翻页
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-3 div").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "#li-3 div")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.switch_to.frame(2)
        self.driver.find_element(By.LINK_TEXT, "2").click()
        self.driver.find_element(By.LINK_TEXT, "1").click()