# –*–coding:utf-8 –*–
# 2021-12-07 14:24
from selenium.webdriver.common.by import By
from selenium.webdriver import ActionChains
from langyun_automate.langyun.page.webdriver_initialzation import CaseLogin

'''园务审批'''
class garden_approval(CaseLogin):
    def test_look_approval_result(self):#  查看园务审批结果
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-7 .img-responsive:nth-child(1)").click()
        self.driver.switch_to.frame(2)
        self.driver.find_element(By.CSS_SELECTOR, ".btn-warning-outline").click()
        self.driver.find_element(By.CSS_SELECTOR, ".text-c:nth-child(1) .cl-tb").click()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.LINK_TEXT, "已同意").click()
        self.driver.switch_to.default_content()
        self.driver.find_element(By.CSS_SELECTOR, ".layui-layer-close").click()
        self.driver.close()

    def test_comment_teaching_plan(self): # 点评教学计划
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-7 div").click()
        self.driver.find_element(By.LINK_TEXT, "班级计划").click()
        element = self.driver.find_element(By.LINK_TEXT, "班级计划")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.switch_to.frame(3)
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.CSS_SELECTOR, ".text-c:nth-child(1) .cl-tb").click()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.NAME, "content").click()
        self.driver.find_element(By.NAME, "content").send_keys("可以可以")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-secondary").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".btn-secondary")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.close()

    def test_comment_term_plan(self): # 点评学期计划
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-7 .img-responsive:nth-child(1)").click()
        self.driver.find_element(By.LINK_TEXT, "学期计划").click()
        element = self.driver.find_element(By.LINK_TEXT, "学期计划")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.switch_to.frame(3)
        self.driver.find_element(By.CSS_SELECTOR, ".text-c:nth-child(1) .cl-tb").click()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.NAME, "content").click()
        self.driver.find_element(By.NAME, "content").send_keys("哈哈哈哈哈")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-secondary").click()
        self.driver.close()

    def test_year_plan(self):# 点评整年计划
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-7 .img-responsive:nth-child(1)").click()
        self.driver.find_element(By.LINK_TEXT, "整年计划").click()
        self.driver.switch_to.frame(3)
        self.driver.find_element(By.CSS_SELECTOR, ".text-c:nth-child(1) .cl-tb").click()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.NAME, "content").click()
        self.driver.find_element(By.NAME, "content").send_keys("啦啦啦啦")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-secondary").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".btn-secondary")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.close()

    def test_comment_work_report(self):# 点评工作总结
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-7 .img-responsive:nth-child(1)").click()
        self.driver.find_element(By.LINK_TEXT, "工作总结").click()
        self.driver.switch_to.frame(3)
        self.driver.find_element(By.CSS_SELECTOR, ".text-c:nth-child(1) .cl-tb").click()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.NAME, "content").click()
        self.driver.find_element(By.NAME, "content").send_keys("1111222")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-secondary").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".btn-secondary")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.close()

    def test_comment_other_plan(self):# 点评其他计划
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.CSS_SELECTOR, "#li-7 .img-responsive:nth-child(1)").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "#li-7 .img-responsive:nth-child(1)")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.LINK_TEXT, "班级计划").click()
        element = self.driver.find_element(By.LINK_TEXT, "班级计划")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.switch_to.frame(3)
        self.driver.find_element(By.LINK_TEXT, "其他计划").click()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.CSS_SELECTOR, ".text-c:nth-child(1) .cl-tb").click()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.NAME, "content").click()
        self.driver.find_element(By.NAME, "content").send_keys("哈哈哈哈哈哈啊哈哈哈")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-secondary").click()
        self.driver.close()

    def test_leave_childrens(self):
        self.driver.set_window_size(1936, 1096)
        self.driver.find_element(By.NAME, "account").click()
        self.driver.find_element(By.NAME, "account").send_keys("13006662818")
        self.driver.find_element(By.NAME, "password").send_keys("langyun")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-secondary").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".btn-secondary")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR, "#li-7 div").click()
        self.driver.switch_to.frame(2)
        self.driver.find_element(By.CSS_SELECTOR, ".text-c:nth-child(1) .cl-tb").click()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.NAME, "info").click()
        self.driver.find_element(By.NAME, "info").send_keys("好的好的")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-secondary").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".btn-secondary")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.ID, "layui-layer-shade1").click()
        self.driver.close()