---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2021-12-20 18:11
---
print('hello world')
function people(name, age)
    self.age =  age
    self.name = name
    return name, age
end
a = 2
a1 = 3.14
a2 = 'a'
a3 = true
print(type(a))
print(type(a1))
print(type(a2))
print(type(a3))
