# coding=utf-8
import time
import unittest
import os
import allure
from page.login_page import LoginPage
from selenium import webdriver
from HTMLTestRunner import HTMLTestRunner

class CaseLogin(unittest.TestCase):
    '''
    朗云登录Case
    '''
    @allure.title("登录成功")
    def setUp(self):
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(10) # 全局隐式等待10s
        self.url = "http://t2.aservice.langlangyun.com:5480/langyun/public/index.php/workplace/pub/login.html"
        self.username = '13006662818'
        self.password = 'langyun'
        

    def testLogin(self):
        login_page = LoginPage(self.driver, self.url, u'后台登录 - 朗云智慧幼教管理平台')
        login_page.open()
        login_page.input_username(self.username)
        time.sleep(2)
        login_page.input_password(self.password)
        login_page.click_submit()
        time.sleep(5)
        assert self.driver.title == u'朗云智慧幼教管理平台', '登录失败'
        self.login_page = login_page

    def tearDown(self):
        self.driver.quit()


if __name__ == '__main__':
    unittest.main(['-s', '--alluredir','result'])
    suite = unittest.TestSuite()
    suite.addTests( unittest.TestLoader().loadTestsFromTestCase( CaseLogin ) )
    filepath = 'D:/Python/langyun_automate/Report'
    if not os.path.exists(filepath):
        os.makedirs(filepath)
    fp = open( './Report/HTMLReport.html' , 'wb' )
    runner = HTMLTestRunner( stream = fp , title = 'MathFunc Test Report' ,
                             description = 'generated by HTMLTestRunner.' , verbosity = 2 )
    runner.run( suite )
    fp.close()
    os.system('allure generate result -o report --clean')
    
